# Generated by Django 3.0.4 on 2020-04-03 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCourseComplaint',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shopWeb.Complaint')),
                ('year', models.CharField(max_length=4)),
                ('course_code', models.CharField(max_length=7)),
                ('description', models.TextField()),
                ('status', models.TextField(default='Registered')),
            ],
        ),
    ]
